import type { ReportDocument, ScanApiResponse, ScoreBreakdown } from "../api/types";

export function makeScore(overrides: Partial<ScoreBreakdown> = {}): ScoreBreakdown {
  return {
    raw_score: "82.0",
    score: 82,
    grade: "B",
    scoring_version: "1.0",
    configured_points: "100.0",
    applicable_points: "100.0",
    evaluated_points: "100.0",
    available_points: "100.0",
    earned_points: "82.0",
    deductions: "18.0",
    coverage: "1.0",
    categories: [
      {
        category: "Transport Security",
        configured_weight: "30.0",
        applicable_points: "30.0",
        evaluated_points: "30.0",
        available_points: "30.0",
        earned_points: "24.0",
        deductions: "6.0",
        normalized_score: "0.8",
        earned_normalized_contribution: "24.0",
        coverage: "1.0",
      },
      {
        category: "Security Headers",
        configured_weight: "25.0",
        applicable_points: "25.0",
        evaluated_points: "25.0",
        available_points: "25.0",
        earned_points: "20.0",
        deductions: "5.0",
        normalized_score: "0.8",
        earned_normalized_contribution: "20.0",
        coverage: "1.0",
      },
    ],
    rule_contributions: [
      {
        rule_id: "TLS-001",
        category: "Transport Security",
        state: "FAIL",
        configured_points: "10.0",
        available_points: "10.0",
        earned_points: "0.0",
        deduction: "10.0",
        credit_fraction: "0.0",
        reason: "The expected transport property was not observed.",
        exclusion_reason: null,
      },
    ],
    exclusions: [],
    cap: null,
    withholding_reasons: [],
    explanation: "The final score and grade are produced by the WebGuard scoring engine.",
    ...overrides,
  };
}

export function makeReport(overrides: Partial<ReportDocument> = {}): ReportDocument {
  return {
    report_schema_version: "1.0",
    webguard_version: "0.1.0.dev0",
    target: {
      scheme: "https",
      hostname: "example.com",
      port: 443,
      path: "/",
      display_url: "https://example.com/",
    },
    scan_metadata: {
      scan_id: "11111111-1111-4111-8111-111111111111",
      started_at: "2026-09-14T10:00:00Z",
      finished_at: "2026-09-14T10:00:01Z",
      duration_ms: 1250,
      webguard_version: "0.1.0.dev0",
      ruleset_version: "1.0",
      redirect_count: 0,
      state: "COMPLETED",
    },
    completion_state: "COMPLETED",
    score: makeScore(),
    severity_summary: [
      { severity: "HIGH", count: 1 },
      { severity: "MEDIUM", count: 1 },
      { severity: "LOW", count: 1 },
      { severity: "INFO", count: 1 },
    ],
    findings: [
      {
        id: "TLS-001",
        title: "TLS certificate validation",
        category: "Transport Security",
        status: "FAIL",
        evaluation_state: "APPLICABLE",
        severity: "HIGH",
        description: "The certificate could not be validated.",
        evidence: [{ label: "Result", value: "certificate verify failed", source_url: null }],
        recommendation: "Install and serve a valid certificate chain.",
        references: ["https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security"],
      },
      {
        id: "HDR-001",
        title: "Content Security Policy",
        category: "Security Headers",
        status: "WARNING",
        evaluation_state: "APPLICABLE",
        severity: "MEDIUM",
        description: "A restrictive policy was not observed.",
        evidence: [{ label: "Header", value: "not present", source_url: "https://example.com/" }],
        recommendation: "Deploy a tested Content-Security-Policy header.",
        references: [],
      },
      {
        id: "CKI-001",
        title: "Cookie attributes",
        category: "Cookie Security",
        status: "WARNING",
        evaluation_state: "APPLICABLE",
        severity: "LOW",
        description: "A cookie can use stronger attributes.",
        evidence: [],
        recommendation: "Review Secure and SameSite attributes.",
        references: [],
      },
      {
        id: "INF-001",
        title: "Server disclosure",
        category: "Information Disclosure / Hygiene",
        status: "INFO",
        evaluation_state: "APPLICABLE",
        severity: "INFO",
        description: "A server product token was observed.",
        evidence: [],
        recommendation: null,
        references: [],
      },
    ],
    operational_errors: [],
    methodology: ["Passive, bounded HTTP observations."],
    limitations: ["This point-in-time assessment does not prove the absence of vulnerabilities."],
    disclaimer: "WebGuard results are informational and are not a guarantee of security.",
    ...overrides,
  };
}

export function makeResponse(reportOverrides: Partial<ReportDocument> = {}): ScanApiResponse {
  return {
    api_version: "v1",
    api_schema_version: "1.0",
    request_id: "22222222-2222-4222-8222-222222222222",
    report: makeReport(reportOverrides),
  };
}
